name: Build and release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25.1"

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2

      - name: Build all binaries using Makefile
        run: make build-all

      - name: Package release artifacts
        run: |
          mkdir -p dist

          mkdir -p tmp/windows
          cp bin/cmit-windows-amd64.exe tmp/windows/cmit.exe
          zip -j dist/cmit-windows-amd64.zip tmp/windows/cmit.exe

          mkdir -p tmp/linux
          cp bin/cmit-linux-amd64 tmp/linux/cmit
          tar -czf dist/cmit-linux-amd64.tar.gz -C tmp/linux cmit

          mkdir -p tmp/darwin
          cp bin/cmit-darwin-amd64 tmp/darwin/cmit
          tar -czf dist/cmit-darwin-amd64.tar.gz -C tmp/darwin cmit

          rm -rf tmp

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: dist/*
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
